### ISSUE TITLE
How to formulate commom network from dynamic network?

### ISSUE THREAD

**Issue by zzllc3** [yanwei-li/DynamicRouting#1]
Could you explain more about the method to formulate common network?

**Comment by yanwei-li** [comment]
This version of code doesn't contain the automatic formulation of common networks, and we will give them soon.  
Actually, it's easy to formulate by giving specific _layer_index_, _cell_index_ and _resolution transform method_  in _DynamicNetwork_ of DynamicRouting/dl_lib/modeling/dynamic_arch/dynamic_backbone.py

**Comment by yanwei-li** [comment]
> Could you explain more about the method to formulate common network?

This version of code doesn't contain the automatic formulation of common networks, and we will give them soon.  
Actually, it's easy to formulate by giving specific _layer_index_, _cell_index_ and _resolution transform method_  in _DynamicNetwork_ of DynamicRouting/dl_lib/modeling/dynamic_arch/dynamic_backbone.py

**Comment by yanwei-li** [comment]
> Could you explain more about the method to formulate common network?

This version doesn't contain the automatic formulation of common networks, and we will give the implementation in the revision.
Actually, it's easy to formulate them by giving specific _layer_index_, _cell_index_ and _resolution transform method_ in _DynamicNetwork_ of dl_lib/modeling/dynamic_arch/dynamic_backbone.py

**Comment by zzllc3** [comment]
Thanks for your reply.
What I want to ask is the rule to formulate common network. Actually, I don't quite understand the following sentence in paper:
_'Furthermore, the fundamental routes of dynamic networks, which are preserved over 95% forward inference, are extracted to formulate corresponding common network.'_
Do you means after dropping the cells which activating factor less than 0, the preserved paths still account for more than 95% of the routing space? But Fig 5 seems to indicate that this is not the case.

**Comment by yanwei-li** [comment]
> Thanks for your reply.
> What I want to ask is the rule to formulate common network. Actually, I don't quite understand the following sentence in paper:
> _'Furthermore, the fundamental routes of dynamic networks, which are preserved over 95% forward inference, are extracted to formulate corresponding common network.'_
> Do you means after dropping the cells which activating factor less than 0, the preserved paths still account for more than 95% of the routing space? But Fig 5 seems to indicate that this is not the case.

Sorry for misunderstanding. Here, _'the fundamental routes which are preserved over 95% forward inference'_ means the route which is most likely to be preserved (95%) when given different images. For example, if the node N_i is preserved (prob>0) over 95 images when given 100 images in total, we keep this node to formulate the _common_ network. This is designed to extract the common trend of learned dynamic patterns.

**Comment by zzllc3** [comment]
> > Thanks for your reply.
> > What I want to ask is the rule to formulate common network. Actually, I don't quite understand the following sentence in paper:
> > _'Furthermore, the fundamental routes of dynamic networks, which are preserved over 95% forward inference, are extracted to formulate corresponding common network.'_
> > Do you means after dropping the cells which activating factor less than 0, the preserved paths still account for more than 95% of the routing space? But Fig 5 seems to indicate that this is not the case.
> 
> Sorry for misunderstanding. Here, _'the fundamental routes which are preserved over 95% forward inference'_ means the route which is most likely to be preserved (95%) when given different images. For example, if the node N_i is preserved (prob>0) over 95 images when given 100 images in total, we keep this node to formulate the _common_ network. This is designed to extract the common trend of learned dynamic patterns.

Thanks a lot.
