### ISSUE TITLE
In deform_conv.py have from dl_lib import _C,but in dl_lib don't  have the function of _C

### ISSUE THREAD

**Issue by flj19951219** [yanwei-li/DynamicRouting#10]

**Comment by yanwei-li** [comment]
Hi! Could you please give more details about the bug? And do you follow the install instruction in README (which requires at least one GPU for compiling)?

**Comment by flj19951219** [comment]
yes，I have one GPU,the install instruction in README is in linux system，but i only have window10 system， so maybe some packet are not install

**Comment by yanwei-li** [comment]
Actually, for the reason that this project is based on Detectron2, which does not officially support Windows, you can use linux system or refer to the solution given by Detectron2 https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md#2-install-from-a-local-clone

Of course, you can also remove the dictionary of "deformable conv", which has not been used in the project.

**Comment by yqshixudong** [comment]
我也是在win10上编译不了，作者能不能其他办法，因为DCN我之前有些代码可以编译的
