### ISSUE TITLE
effectiveness of the scheduled drop path

### ISSUE THREAD

**Issue by ShoufaChen** [yanwei-li/DynamicRouting#11]
Hi,

I wonder whether it is clear to prove the effectiveness of the  Scheduled Drop Path (SDP)?

Models with SDP  are trained with more iteration (the third row).
And the best result is trained with ImageNet pre-train but without SDP.

Thanks in advance.

**Comment by yanwei-li** [comment]
Hi! SDP is used to prevent overfitting when training from scratch. And if the ImageNet pre-trained model is utilized for initialization, the SDP will not have much contributions in our model. So, we do not use the SDP for the final model (use ImageNet pretrain).

**Comment by ShoufaChen** [comment]
Thank you for your reply.

I wonder how much contribution does SDP have for training from scratch?

Because the experiments with SDP are trained with more iterations, it is not clear which one brings the performance gain. SDP or more iteration.

**Comment by yanwei-li** [comment]
If SDP is droped with too much training (without ImageNet pretrain), the network is easy to overfitting and achieve no more gains compared with less iters. So, it could be necessary to use SDP if trained with long iters.

**Comment by ShoufaChen** [comment]
Thank you very much for your reply.
