### ISSUE TITLE
关于程序输出目录的问题

### ISSUE THREAD

**Issue by wo712268** [yanwei-li/DynamicRouting#14]
作者你好！我在pytorch1.5.1上成功运行了setup.py并且按照指令输入了：
   cd playground/Dynamic/Seg.Layer16
    dl_train --num-gpus 4
但是一直都没有输出，我在程序主文件夹下创建了output, instant_test_output和inference_test_output，ignore文件也识别了这三个文件夹，修改了config.py里的OUT DIR为./output，但还是没有输出，生成的log链接文件一直是红色的，双击log显示链接目录失败。
我是不是哪一步还没做？

**Comment by yanwei-li** [comment]
Hi, maybe you could use the real path to set the OUT_DIR rather than using the relative one.
