### ISSUE TITLE
setup.py SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tianmingdu** [yanwei-li/DynamicRouting#15]
After running the command 'sudo python3 setup.py build develop', following error alerts. 

File "setup.py", line 65
    head = f"#!/bin/bash\n\nexport OMP_NUM_THREADS=1\n"
                                                                                                  ^
SyntaxError: invalid syntax

**Comment by yanwei-li** [comment]
Hi, it seems like the typo in code format, which not exists in my running. Maybe you can reformulate the corresponding code and run it again.

**Comment by ShihuaHuang95** [comment]
@tianmingdu Same question. Have you fixed?
