### ISSUE TITLE
About initialization of BIAS in gate conv

### ISSUE THREAD

**Issue by Sixkplus** [yanwei-li/DynamicRouting#16]
I noticed that in the paper, you mentioned that 

The weights in convolutions are initialized with normal distribution [15] while the bias /beta in Eq. 2 is initialized to a constant value 1.5 experimentally.

I am wondering what will the performance become if I set this constant to 0? Have you tried this variant and obtain any conclusion?

**Comment by yanwei-li** [comment]
Hi, we initialize the bias /beta with a constant 1.5 to ensure that **_the mean activating prob of each node could surpass 0.9_** (tanh(1.5)>0.9), which ensures each path is selected for optimization from the beginning. 

If this constant is set to 0, a huge amount of gates could tend to be closed at the begining and the params in it could not be optimized well, which would bring performance drop.

**Comment by Sixkplus** [comment]
@yanwei-li 
Thank you for your reply.
I'm still curious about the threshold. It seems that the cell is dropped if tanh(gate_weight) < 0.0001, then is it necessary to set such a large bias?

**Comment by yanwei-li** [comment]
Hi, we set the bias to 1.5 experimentally. And a small initial value would bring the performance drop.

**Comment by Sixkplus** [comment]
All right. Thank you for your reply
