### ISSUE TITLE
the _C file needed

### ISSUE THREAD

**Issue by MiarLee** [yanwei-li/DynamicRouting#17]
hello，in your code,you have called a file in the dl_lib directory named _C,but i cannot find this file.Could you please tell me the effect of this file ,and where is it.thank you!

**Comment by yanwei-li** [comment]
Hi, do you compile the source code in the Linux environment with at least one GPU? 
Maybe you can refer to issue #10

**Comment by MiarLee** [comment]
follow your instructions compile the source code, the errors occured as:No module named torch,but my Linux environment has installed torch,and other project can run normally.Could you please tell me which pyrhon file to start your code.I try train_net.py,but failed.

**Comment by yanwei-li** [comment]
Hi, maybe you could follow the guideline in README. 
`cd playground/Dynamic/Seg.Layer16`
`dl_train --num-gpus 4`
