### ISSUE TITLE
目前公布的代码是完整的代码吗？

### ISSUE THREAD

**Issue by xlh1135355585** [yanwei-li/DynamicRouting#18]
请问目前公布的代码是完整的代码吗？

**Comment by yanwei-li** [comment]
Hi, the released code includes the main results for semantic segmentation in the paper.

**Comment by xlh1135355585** [comment]
Is the currently published code the main part of the article?

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanwei <notifications@github.com&gt;
发送时间: 2020年7月27日 14:55
收件人: yanwei-li/DynamicRouting <DynamicRouting@noreply.github.com&gt;
抄送: xlh1135355585 <1135355585@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yanwei-li/DynamicRouting] 目前公布的代码是完整的代码吗？ (#18)





 
Hi, the released code includes the main results for semantic segmentation in the paper.

**Comment by yanwei-li** [comment]
Yes, you can find the experiments with different settings in `playground/Dynamic/`.

**Comment by MandyMo** [comment]
问一下，搜索相关的代码在哪呢？

**Comment by yanwei-li** [comment]
> 问一下，搜索相关的代码在哪呢？

Actually, we do not search for a specific architecture for inference. In the inference stage, the generated network architecture adapt to input images.

**Comment by MandyMo** [comment]
多谢回复，明白了。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanwei <notifications@github.com&gt;
发送时间: 2020年8月4日 11:52
收件人: yanwei-li/DynamicRouting <DynamicRouting@noreply.github.com&gt;
抄送: zhang xiong <1025679612@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[yanwei-li/DynamicRouting] 目前公布的代码是完整的代码吗？ (#18)





  
问一下，搜索相关的代码在哪呢？
  
Actually, we do not search for a specific architecture for inference. In the inference stage, the generated network architecture adapt to input images.
