### ISSUE TITLE
max iteration and training time

### ISSUE THREAD

**Issue by ShoufaChen** [yanwei-li/DynamicRouting#6]
Hi, 
Thanks for your open-source. 

I noticed that the `SOLVER.MAX_EPOCH` is 190k in [config.py](https://github.com/yanwei-li/DynamicRouting/blob/master/playground/Dynamic/Seg.Layer16.SmallGate.Dynamic_A/config.py#L48). But the iter is 186k  in the `README` table.  Though the difference is minor,  I wonder what's the exact value.

Besides, how long does it take to finish the training?

Thanks in advance.

**Comment by yanwei-li** [comment]
Sorry for the confusion. Actually, both are right and the difference between them is minor. To save the model at 10K iters, we set the total iter to 190K just for convenience.

**Comment by ShoufaChen** [comment]
Thank you for your reply
