### ISSUE TITLE
Abuot the results of Auto-DeepLab used in the paper.

### ISSUE THREAD

**Issue by ShoufaChen** [yanwei-li/DynamicRouting#9]
Hi,

I noticed that the results of Auto-DeepLab are significantly different from the original Auto-Deeplab. 

So what makes these differences?

**Comment by yanwei-li** [comment]
Hi! We model the raw connection pattern of Auto-DeepLab (NOT including the operations inside nodes) using the proposed dynamic routing space in Table 1 (training from scratch), which is claimed in the caption of Table 1. And we compare with the raw auto-deeplab in Table 6 & 7.

**Comment by ShoufaChen** [comment]
Thank you for your reply.
